apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: test-autoscaler
  labels:
    app: test-app
spec:
  selector:        
    app: test-app
  type: NodePort    
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30500 